header:
  Access-Control-Allow-Origin: "*"
  Access-Control-Allow-Methods: "*"
  Access-Control-Allow-Headers: "*"
log_level: debug
port: 9080
host_conf:
  api.xxx.com:
    header:
      Authorization: "Bearer {token}"